# Generated by Django 6.1 on 2026-09-03 13:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChairVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('ML', 'Masala Chai'), ('GT', 'Green Tea'), ('BT', 'Black Tea'), ('HT', 'Herbal Tea'), ('OT', 'Oolong Tea')], default='ML', max_length=2)),
            ],
        ),
    ]
