# Generated by Django 6.1 on 2026-09-03 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChairVariety',
            new_name='ChaiVariety',
        ),
    ]
