# Generated by Django 6.1 on 2026-09-07 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_rename_chairvariety_chaivariety'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
    ]
